apiVersion: v1
kind: Pod
metadata:
  name: img-loader
  namespace: symc
spec:
  nodeName: k8s-wk-01
  restartPolicy: Never
  containers:
  - name: loader
    image: debian:bookworm-slim
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    volumeMounts:
    - { name: host-bin, mountPath: /host-bin }
    - { name: host-tmp, mountPath: /host-tmp }
    - { name: containerd-sock, mountPath: /run/containerd }
  volumes:
  - { name: host-bin, hostPath: { path: /usr/bin } }
  - { name: host-tmp, hostPath: { path: /tmp } }
  - { name: containerd-sock, hostPath: { path: /run/containerd } }
