apiVersion: v1
kind: Pod
metadata:
  name: jar-updater
  namespace: symc
spec:
  nodeName: k8s-wk-01
  restartPolicy: Never
  containers:
  - name: updater
    image: debian:bookworm-slim
    command: ["sleep", "1800"]
    resources:
      requests: { cpu: 50m, memory: 64Mi }
    volumeMounts:
    - { name: paper-home, mountPath: /opt/paper }
  volumes:
  - { name: paper-home, hostPath: { path: /tmp/paper, type: DirectoryOrCreate } }
