settings:
  allow-end: true
  warn-on-overload: false
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 5
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
aliases:
  now: paper
timeout-time: 60
restart-on-crash: true
world-settings:
  default:
    verbose: false
    mob-spawn-range: 6
    merge-radius:
      item: 2.5
      exp: 3.0
    mob-spawn-frequency: 1
    arrow-despawn-rate: 300
    allow-rename: true
