accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=easy
enable-command-block=true
enable-rcon=true
enable-status=true
enforce-secure-profile=true
gamemode=survival
generate-structures=true
hardcore=false
max-players=20
max-tick-time=60000
motd=Symc Test Server - Distributed MC Sync Engine
network-compression-threshold=256
online-mode=false
prevent-proxy-connections=false
pvp=true
query.port=25565
rcon.password=symc
rcon.port=25575
server-port=25565
simulation-distance=8
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
use-native-transport=true
view-distance=8
white-list=false
